
backend:
  name: git-gateway
  branch: master
  commit_message:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'


media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/data/blog'
    create: true
    slug: "{{year}}-{{month}}-{{day}}"
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'CoverImage', name: 'cover', widget: 'image'}
      - { label: 'Author', name: 'author', widget: 'string'}
      - { label: 'Body', name: 'body', widget: 'markdown' }