
backend:
  name: git-gateway
  branch: master
  commit_message:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'


media_folder: static/img
public_folder: /img

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}"
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "blogTemplate"}
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', date_format: "YYYY-MM-DD" }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'CoverImage', name: 'cover', widget: 'image'}
      - { label: 'Author', name: 'author', widget: 'string'}
      - { label: 'Body', name: 'body', widget: 'markdown' }
  
  - name: service
    label: Service
    folder: content/services
    slug: '{{slug}}'
    create: true
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "serviceTemplate"}
      - { label: 'Title', name: 'title', widget: 'string'}
      - { label: 'OnboardTitle', name: 'onboardTitle', widget: 'string'}
      - { label: 'OnboardDescription', name: 'onboardDescription', widget: 'string'}
      - { label: 'OnboardImg', name: 'onboardImg', widget: 'image'}
      - { label: 'BlogLink', name: 'blogLink', widget: 'string'}
      - { label: 'OtherServiceTitle', name: 'otherServiceTitle', widget: 'string'}
      - { label: 'OtherServiceLink', name: 'otherServiceLink', widget: 'string'}
      - { label: 'OtherServiceDescription', name: 'otherServiceDescription', widget: 'string'}
      - label: 'Benefits'
        name: 'benefits'
        widget: 'object'
        fields: 
          - { label: BenefitTitle, name: benefitTitle, widget: 'string' }
            { label: BenefitDescription, name: benefitDescription, widget: 'string' }
            { label: BenefitImg, name: benefitImg, widget: 'image' }
          - { label: BenefitTitle, name: benefitTitle, widget: 'string' }
            { label: BenefitDescription, name: benefitDescription, widget: 'string' }
            { label: BenefitImg, name: benefitImg, widget: 'image' }
          - { label: BenefitTitle, name: benefitTitle, widget: 'string' }
            { label: BenefitDescription, name: benefitDescription, widget: 'string' }
            { label: BenefitImg, name: benefitImg, widget: 'image' }
          - { label: BenefitTitle, name: benefitTitle, widget: 'string' }
            { label: BenefitDescription, name: benefitDescription, widget: 'string' }
            { label: BenefitImg, name: benefitImg, widget: 'image' }
      - label: 'Workflow'
        name: 'workflow'
        widget: 'object'
        fields: 
          - { label: StepTitle, name: stepTitle, widget: 'string' }
            { label: StepDescription, name: stepDescription, widget: 'string' }
            { label: StepImg, name: stepImg, widget: 'image' }
          - { label: StepTitle, name: stepTitle, widget: 'string' }
            { label: StepDescription, name: stepDescription, widget: 'string' }
            { label: StepImg, name: stepImg, widget: 'image' }
          - { label: StepTitle, name: stepTitle, widget: 'string' }
            { label: StepDescription, name: stepDescription, widget: 'string' }
            { label: StepImg, name: stepImg, widget: 'image' }
          - { label: StepTitle, name: stepTitle, widget: 'string' }
            { label: StepDescription, name: stepDescription, widget: 'string' }
            { label: StepImg, name: stepImg, widget: 'image' }


